// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRSTzwGE0IF7ZvN1J6-O0s6oxdIMlnIvM',
    appId: '1:259010923168:web:7664185d461df284edd7c5',
    messagingSenderId: '259010923168',
    projectId: 'tum-kenya',
    authDomain: 'tum-kenya.firebaseapp.com',
    databaseURL: 'https://tum-kenya-default-rtdb.firebaseio.com',
    storageBucket: 'tum-kenya.appspot.com',
    measurementId: 'G-NP9T756MNF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCH6p2QwhqvM033wgUCPwVp1y5S-ctQoy0',
    appId: '1:259010923168:android:331000eade6b1062edd7c5',
    messagingSenderId: '259010923168',
    projectId: 'tum-kenya',
    databaseURL: 'https://tum-kenya-default-rtdb.firebaseio.com',
    storageBucket: 'tum-kenya.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9Fy_joYPIz-ivnd-PJzTUkID7ENk9vWs',
    appId: '1:259010923168:ios:1c94cb823310beadedd7c5',
    messagingSenderId: '259010923168',
    projectId: 'tum-kenya',
    databaseURL: 'https://tum-kenya-default-rtdb.firebaseio.com',
    storageBucket: 'tum-kenya.appspot.com',
    androidClientId: '259010923168-2bh3lb8643hv65jova40kqgmsggaf6pa.apps.googleusercontent.com',
    iosClientId: '259010923168-2beina25a5ufog42mafse0lnev7385i1.apps.googleusercontent.com',
    iosBundleId: 'com.tum.app.tum',
  );
}
